export const SCHOOL_CONFIG = {
  namaSekolah: 'SMK Muhammadiyah Bawang',
  namaPendek: 'SMK Muhiba',
  majlis: 'MAJLIS PENDIDIKAN DASAR DAN MENENGAH',
  daerah: 'DAERAH MUHAMMADIYAH BATANG',
  akreditasi: 'TERAKREDITASI "A"',
  alamat: 'Jl. Bawang-Sukorejo Km 01 Ds. Jlamprang Kec. Bawang Kab. Batang.',
  telepon: '(0285) 4486909',
  fax: '(0285) 4486899',
  kodePos: '51274',
  email: 'smkmuhbawang@gmail.com',
  website: 'www.smkmuhiba.sch.id',
  websiteUrl: 'https://www.smkmuhiba.sch.id',
  logoUrl: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgzWdtCjCcX2chJuhLX_26N5MmkVK-1SkyO7kgXznQQJPQa6_TB_EJzD1WWpztg7yX9RBRE7rGn0t2Z3FdG06mwwT6pQix8t6vnlcOBm_EgGl9z0jeJemJkppP0KIIjkXGksQvaCLh2dz-gOF6a2H213VQBL6Am8Elhmd76OOnphogk-EoTTbkYbg0TQJhv/s512/34690.png',
  logoFallback: '/logo-smk.png',
  bgImageUrl: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh14eQT9MWn4-D1hdb8FisPsg0qK1iIvxXbMg0RGCvXFzUVWUt_KTiOWcEBzrJYxqALWV7_RPeowvTNfbyw-tbCeDb40lvY5jm_lWN5_jjeZko2SF82_wLRcW2-rBs6fWcauvugbRXBRODAeDb0FBkV81rSrgh6stKQG9ZWf5MU3qxTwiqdSEO9AaJ1EbUX/s480/44857.png',
  bgImageFallback: '/bg-school.png',
  kurikulum: 'Kurikulum Merdeka',
  tahunAjaran: '2025/2026',
  semester: 'Genap',
};

export const JURUSAN_OPTIONS = [
  'Teknik Otomotif',
  'TJKT',
  'Akuntansi dan Keuangan Lembaga',
  'Perbankan Syari\'ah',
  'TKR',
  'TSM',
  'TKJ',
  'TJAT',
] as const;
